services:
  chat-app:
    container_name: chat-app
    image: chat-app
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
  rabbitmq:
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
      - '15672:15672'
